language: python
python:
    - "2.7"
    # command to install dependencies
    install: "sudo python setup.py install"
    # command to run tests
    before_script: "/bin/sh test/travis_setup.sh"
    script: "nosetests"